### ISSUE TITLE
Automate unit tests

### ISSUE THREAD

**Issue by samsymons** [wpp/xander#12]
@wpp Should we set up CircleCI to run the tests on PRs before they are merged? It would be time consuming having to do it manually.

**Comment by wpp** [comment]
That would be great! I have never used CircleCI, if you know how to set that up I'd be all for it.

**Comment by samsymons** [comment]
CircleCI is really great. 😄 We should be able to tie it into the PR flow so that it will run those automatically too. I'll check that out today, been a while since I have used Circle.

**Comment by wpp** [comment]
Builds are running now. However, I'd like to have webhooks show up in the PR's too.

**Comment by samsymons** [comment]
PR #11 confirms that CircleCI is now working. Closing this!
