### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by wpp** [wpp/xander#17]
Someone mentioned the need for a help command.
Sounds like a good idea to me.

**Comment by samsymons** [comment]
This would be really good. Should each response have its own output for how it should be used, maybe in the form of a `help` method? Then at runtime we can dynamically grab all `Response` subclasses and call `help` on them, collecting the results. That would make it easy to add new responses and have them automatically part of the help feature.

**Comment by wpp** [comment]
That sounds perfect, that way we'd also have some documentation directly in the class. #doublekill

von meinem iPhone gesendet

**Comment by wpp** [comment]
There are people watching this...

**Comment by samsymons** [comment]
😱
