### ISSUE TITLE
Feature: Time wasted on destiny

### ISSUE THREAD

**Issue by wpp** [wpp/xander#3]
Like you suggested @samsymons.

Maybe even have a ranking, like the elo-ranking command?
1. samsymons 2000 hours
2. ollyc (xbox + psn) 1000 hours
3. wpp31 500 hours

(Folks on both platforms would need to be added.) Not sure where to get this stuff.

**Comment by samsymons** [comment]
I'll build this feature using [this API](https://www.wastedondestiny.com/api/); example output: https://www.wastedondestiny.com/api/?console=2&user=samsymons
